let dados = [
    {
        titulo: 'Bastardos Inglórios',
        lancamento: '2009',
        descricao: 'Uma reimaginação visceral da Segunda Guerra Mundial, onde um grupo de soldados judeus americanos se infiltra na França ocupada para eliminar nazistas, enquanto uma jovem judia planeja sua vingança. O filme combina ação, suspense e diálogos afiados.',
        genero: 'Ação, Drama, Guerra',
        diretor: 'Quentin Tarantino',
        cast: 'Brad Pitt, Christoph Waltz, Mélanie Laurent, Diane Kruger',
        duracao: '153 minutos',
        rating: '8.3/10',
        streaming: 'Netflix, Amazon Prime Video',
        link: 'https://www.imdb.com/title/tt0361748/'
    },
    {
        titulo: 'Clube da Luta',
        lancamento: '1999',
        descricao: 'Um homem insone e insatisfeito com sua vida encontra um estranho sabão que o leva a um submundo de violência e caos, onde homens se reúnem para lutar secretamente.',
        genero: 'Drama, Thriller',
        diretor: 'David Fincher',
        cast: 'Edward Norton, Brad Pitt, Helena Bonham Carter',
        duracao: '139 minutos',
        rating: '8.8/10',
        streaming: 'HBO Max',
        link: 'https://www.imdb.com/title/tt0137523/'
    },
    {
        titulo: 'Um Sonho de Liberdade',
        lancamento: '1994',
        descricao: 'Um homem injustamente condenado à prisão luta por sua liberdade, planejando uma fuga meticulosa durante décadas.',
        genero: 'Drama',
        diretor: 'Frank Darabont',
        cast: 'Tim Robbins, Morgan Freeman, Bob Gunton',
        duracao: '142 minutos',
        rating: '9.3/10',
        streaming: 'HBO Max',
        link: 'https://www.imdb.com/title/tt0111161/'
    },
    {
        titulo: 'O Poderoso Chefão',
        lancamento: '1972',
        descricao: 'A saga da família Corleone, um dos clãs mafiosos mais poderosos dos Estados Unidos, e a ascensão de Michael Corleone ao poder.',
        genero: 'Crime, Drama',
        diretor: 'Francis Ford Coppola',
        cast: 'Marlon Brando, Al Pacino, James Caan',
        duracao: '175 minutos',
        rating: '9.2/10',
        streaming: 'Paramount+',
        link: 'https://www.imdb.com/title/tt0068646/'
    },
    {
        titulo: 'O Senhor dos Anéis: A Sociedade do Anel',
        lancamento: '2001',
        descricao: 'Um hobbit encontra um anel mágico que pode dominar o mundo e embarca em uma jornada épica para destruí-lo.',
        genero: 'Aventura, Fantasia',
        diretor: 'Peter Jackson',
        cast: 'Elijah Wood, Ian McKellen, Viggo Mortensen',
        duracao: '201 minutos',
        rating: '8.8/10',
        streaming: 'Amazon Prime Video',
        link: 'https://www.imdb.com/title/tt0120737/'
    },
    {
        titulo: 'Pulp Fiction',
        lancamento: '1994',
        descricao: 'Várias histórias interligadas se desenrolam em Los Angeles, com personagens excêntricos envolvidos em crimes e situações bizarras.',
        genero: 'Crime, Drama',
        diretor: 'Quentin Tarantino',
        cast: 'John Travolta, Samuel L. Jackson, Uma Thurman',
        duracao: '154 minutos',
        rating: '8.9/10',
        streaming: 'Netflix',
        link: 'https://www.imdb.com/title/tt0110912/'
    },
    {
        titulo: 'O Iluminado',
        lancamento: '1980',
        descricao: 'Um escritor em crise leva sua família para um hotel isolado no inverno, onde forças sobrenaturais o levam à loucura.',
        genero: 'Terror, Suspense',
        diretor: 'Stanley Kubrick',
        cast: 'Jack Nicholson, Shelley Duvall, Danny Lloyd',
        duracao: '146 minutos',
        rating: '8.7/10',
        streaming: 'HBO Max',
        link: 'https://www.imdb.com/title/tt0078788/'
    },
    {
        titulo: 'O Poderoso Chefão II',
        lancamento: '1974',
        descricao: 'A continuação épica da saga Corleone, explorando a ascensão e queda de Michael Corleone.',
        genero: 'Crime, Drama',
        diretor: 'Francis Ford Coppola',
        cast: 'Al Pacino, Robert De Niro, Diane Keaton',
        duracao: '202 minutos',
        rating: '9.0/10',
        streaming: 'Paramount+',
        link: 'https://www.imdb.com/title/tt0075784/'
    },
    {
        titulo: 'A Lista de Schindler',
        lancamento: '1993',
        descricao: 'A história real de Oskar Schindler, um empresário alemão que salvou mais de mil judeus do Holocausto.',
        genero: 'Drama, História',
        diretor: 'Steven Spielberg',
        cast: 'Liam Neeson, Ben Kingsley, Ralph Fiennes',
        duracao: '195 minutos',
        rating: '8.9/10',
        streaming: 'Netflix',
        link: 'https://www.imdb.com/title/tt0108052/'
    },
    {
        titulo: 'O Cavaleiro das Trevas',
        lancamento: '2008',
        descricao: 'Uma nova versão do Batman, onde o herói se confronta com o Coringa, um vilão anárquico e psicopata.',
        genero: 'Ação, Aventura',
        diretor: 'Christopher Nolan',
        cast: 'Christian Bale, Heath Ledger, Aaron Eckhart',
        duracao: '152 minutos',
        rating: '9.0/10',
        streaming: 'HBO Max',
        link: 'https://www.imdb.com/title/tt0468550/'
    },
    {
        titulo: 'Parasita',
        lancamento: '2019',
        descricao: 'Uma família pobre se infiltra na vida de uma família rica, expondo as desigualdades sociais e as consequências de suas ações.',
        genero: 'Drama, Thriller',
        diretor: 'Bong Joon-ho',
        cast: 'Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong',
        duracao: '132 minutos',
        rating: '8.6/10',
        streaming: 'Netflix',
        link: 'https://www.imdb.com/title/tt6759218/'
    },
    {
        titulo: 'La La Land: Cantando Estações',
        lancamento: '2016',
        descricao: 'Um pianista de jazz e uma aspirante a atriz se apaixonam em Los Angeles, enquanto perseguem seus sonhos.',
        genero: 'Musical, Romance',
        diretor: 'Damien Chazelle',
        cast: 'Ryan Gosling, Emma Stone, John Legend',
        duracao: '128 minutos',
        rating: '8.1/10',
        streaming: 'HBO Max',
        link: 'https://www.imdb.com/title/tt3783788/'
    },
    {
        titulo: 'Mad Max: Estrada da Fúria',
        lancamento: '2015',
        descricao: 'Em um futuro pós-apocalíptico, uma guerreira acompanha um grupo de rebeldes em uma jornada através de um deserto devastado.',
        genero: 'Ação, Aventura',
        diretor: 'George Miller',
        cast: 'Tom Hardy, Charlize Theron, Nicholas Hoult',
        duracao: '120 minutos',
        rating: '8.1/10',
        streaming: 'HBO Max',
        link: 'https://www.imdb.com/title/tt1392174/'
    },
    {
        titulo: 'O Labirinto do Fauno',
        lancamento: '2006',
        descricao: 'Uma menina de 13 anos encontra um mundo fantástico em um labirinto enquanto a Espanha está sob ocupação fascista.',
        genero: 'Fantasia, Drama',
        diretor: 'Guillermo del Toro',
        cast: 'Ivana Baquero, Sergi López, Maribel Verdú',
        duracao: '118 minutos',
        rating: '8.2/10',
        streaming: 'Netflix',
        link: 'https://www.imdb.com/title/tt0457470/'
    },
    {
        titulo: 'A Vida de Brian',
        lancamento: '1979',
        descricao: 'Uma sátira cômica sobre a vida de Jesus Cristo, vista através dos olhos de um homem nascido no mesmo dia e lugar.',
        genero: 'Comédia',
        diretor: 'Terry Gilliam',
        cast: 'Graham Chapman, John Cleese, Terry Jones',
        duracao: '94 minutos',
        rating: '8.0/10',
        streaming: 'HBO Max',
        link: 'https://www.imdb.com/title/tt0079442/'
    },
    {
        titulo: 'Interestelar',
        lancamento: '2014',
        descricao: 'Um grupo de exploradores espaciais viaja através de um buraco de minhoca na tentativa de encontrar um novo lar para a humanidade, enquanto enfrentam desafios físicos e emocionais.',
        genero: 'Aventura, Drama, Ficção Científica',
        diretor: 'Christopher Nolan',
        cast: 'Matthew McConaughey, Anne Hathaway, Jessica Chastain',
        duracao: '169 minutos',
        rating: '8.6/10',
        streaming: 'HBO Max, Amazon Prime Video',
        link: 'https://www.imdb.com/title/tt0816692/'
    },
    {
        titulo: 'A Origem',
        lancamento: '2010',
        descricao: 'Um ladrão que rouba segredos corporativos através do uso de tecnologia de compartilhamento de sonhos é dado a tarefa inversa de plantar uma ideia na mente de um CEO.',
        genero: 'Ação, Aventura, Ficção Científica',
        diretor: 'Christopher Nolan',
        cast: 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page',
        duracao: '148 minutos',
        rating: '8.8/10',
        streaming: 'HBO Max, Netflix',
        link: 'https://www.imdb.com/title/tt1375666/'
    },
    {
        titulo: 'Forrest Gump: O Contador de Histórias',
        lancamento: '1994',
        descricao: 'Através dos olhos de Forrest Gump, um homem com QI baixo, vemos os eventos mais importantes da história americana na segunda metade do século 20.',
        genero: 'Drama, Romance',
        diretor: 'Robert Zemeckis',
        cast: 'Tom Hanks, Robin Wright, Gary Sinise',
        duracao: '142 minutos',
        rating: '8.8/10',
        streaming: 'Netflix, Amazon Prime Video',
        link: 'https://www.imdb.com/title/tt0109830/'
    },
    {
        titulo: 'Gladiador',
        lancamento: '2000',
        descricao: 'Um general romano é traído e sua família é assassinada por um imperador corrupto. Ele se torna um gladiador para vingar seus entes queridos.',
        genero: 'Ação, Aventura, Drama',
        diretor: 'Ridley Scott',
        cast: 'Russell Crowe, Joaquin Phoenix, Connie Nielsen',
        duracao: '155 minutos',
        rating: '8.5/10',
        streaming: 'Netflix, Amazon Prime Video',
        link: 'https://www.imdb.com/title/tt0172495/'
    },
    {
        titulo: 'Cidade de Deus',
        lancamento: '2002',
        descricao: 'A vida de dois jovens em uma favela violenta do Rio de Janeiro, um que se torna fotógrafo e outro que se torna um criminoso.',
        genero: 'Crime, Drama',
        diretor: 'Fernando Meirelles, Kátia Lund',
        cast: 'Alexandre Rodrigues, Leandro Firmino, Phellipe Haagensen',
        duracao: '130 minutos',
        rating: '8.6/10',
        streaming: 'Amazon Prime Video, Globoplay',
        link: 'https://www.imdb.com/title/tt0317248/'
    },
    {
        titulo: 'Coringa',
        lancamento: '2019',
        descricao: 'A origem de um dos vilões mais icônicos do universo Batman, explorando como Arthur Fleck se transforma no Coringa.',
        genero: 'Crime, Drama, Thriller',
        diretor: 'Todd Phillips',
        cast: 'Joaquin Phoenix, Robert De Niro, Zazie Beetz',
        duracao: '122 minutos',
        rating: '8.4/10',
        streaming: 'HBO Max',
        link: 'https://www.imdb.com/title/tt7286456/'
    },
    {
        titulo: 'Matrix',
        lancamento: '1999',
        descricao: 'Um hacker descobre que o mundo ao seu redor é uma simulação controlada por máquinas e se junta a uma rebelião para libertar a humanidade.',
        genero: 'Ação, Ficção Científica',
        diretor: 'Lana Wachowski, Lilly Wachowski',
        cast: 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss',
        duracao: '136 minutos',
        rating: '8.7/10',
        streaming: 'Netflix, HBO Max',
        link: 'https://www.imdb.com/title/tt0133093/'
    },
    {
        titulo: 'O Silêncio dos Inocentes',
        lancamento: '1991',
        descricao: 'Uma jovem agente do FBI busca a ajuda de um canibal preso para capturar outro assassino em série.',
        genero: 'Crime, Drama, Thriller',
        diretor: 'Jonathan Demme',
        cast: 'Jodie Foster, Anthony Hopkins, Lawrence A. Bonney',
        duracao: '118 minutos',
        rating: '8.6/10',
        streaming: 'HBO Max, Amazon Prime Video',
        link: 'https://www.imdb.com/title/tt0102926/'
    },
    {
        titulo: 'Whiplash: Em Busca da Perfeição',
        lancamento: '2014',
        descricao: 'Um jovem baterista ambicioso se inscreve em um conservatório de música e é ensinado por um instrutor implacável que não se detém em humilhá-lo.',
        genero: 'Drama, Música',
        diretor: 'Damien Chazelle',
        cast: 'Miles Teller, J.K. Simmons, Melissa Benoist',
        duracao: '107 minutos',
        rating: '8.5/10',
        streaming: 'Amazon Prime Video',
        link: 'https://www.imdb.com/title/tt2582802/'
    },
    {
        titulo: 'A Rede Social',
        lancamento: '2010',
        descricao: 'A história da criação do Facebook e as batalhas legais que surgiram entre seus fundadores.',
        genero: 'Biografia, Drama',
        diretor: 'David Fincher',
        cast: 'Jesse Eisenberg, Andrew Garfield, Justin Timberlake',
        duracao: '120 minutos',
        rating: '7.7/10',
        streaming: 'Netflix',
        link: 'https://www.imdb.com/title/tt1285016/'
    },
    {
        titulo: 'O Grande Hotel Budapeste',
        lancamento: '2014',
        descricao: 'As aventuras de Gustave H, um lendário concierge de um famoso hotel europeu entre as duas guerras mundiais, e Zero Moustafa, o mensageiro que se torna seu amigo de confiança.',
        genero: 'Aventura, Comédia, Crime',
        diretor: 'Wes Anderson',
        cast: 'Ralph Fiennes, F. Murray Abraham, Mathieu Amalric',
        duracao: '99 minutos',
        rating: '8.1/10',
        streaming: 'Disney+, Amazon Prime Video',
        link: 'https://www.imdb.com/title/tt2278388/'
    },
    {
        titulo: 'Blade Runner 2049',
        lancamento: '2017',
        descricao: 'Trinta anos após os eventos do primeiro filme, um novo Blade Runner, o Oficial K da polícia de Los Angeles, descobre um segredo há muito enterrado que tem o potencial de mergulhar o que resta da sociedade no caos.',
        genero: 'Ação, Drama, Ficção Científica',
        diretor: 'Denis Villeneuve',
        cast: 'Ryan Gosling, Harrison Ford, Ana de Armas',
        duracao: '164 minutos',
        rating: '8.0/10',
        streaming: 'HBO Max',
        link: 'https://www.imdb.com/title/tt1856101/'
    },
    {
        titulo: 'A Chegada',
        lancamento: '2016',
        descricao: 'Uma linguista é recrutada pelo exército dos EUA para se comunicar com extraterrestres que chegaram à Terra, enquanto o mundo está à beira da guerra.',
        genero: 'Drama, Mistério, Ficção Científica',
        diretor: 'Denis Villeneuve',
        cast: 'Amy Adams, Jeremy Renner, Forest Whitaker',
        duracao: '116 minutos',
        rating: '7.9/10',
        streaming: 'Amazon Prime Video',
        link: 'https://www.imdb.com/title/tt2543164/'
    },
    {
        titulo: 'O Fabuloso Destino de Amélie Poulain',
        lancamento: '2001',
        descricao: 'Amélie é uma jovem peculiar que decide mudar a vida das pessoas ao seu redor enquanto lida com sua própria solidão.',
        genero: 'Comédia, Romance',
        diretor: 'Jean-Pierre Jeunet',
        cast: 'Audrey Tautou, Mathieu Kassovitz, Rufus',
        duracao: '122 minutos',
        rating: '8.3/10',
        streaming: 'HBO Max',
        link: 'https://www.imdb.com/title/tt0211915/'
    },
    {
        titulo: 'O Regresso',
        lancamento: '2015',
        descricao: 'Após ser atacado por um urso e deixado para morrer, um explorador busca vingança contra aqueles que o traíram.',
        genero: 'Aventura, Drama, Faroeste',
        diretor: 'Alejandro G. Iñárritu',
        cast: 'Leonardo DiCaprio, Tom Hardy, Will Poulter',
        duracao: '156 minutos',
        rating: '8.0/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt1663202/'
    },
    {
        titulo: 'Laranja Mecânica',
        lancamento: '1971',
        descricao: 'No futuro distópico da Inglaterra, Alex DeLarge e sua "gangue" se envolvem em ultraviolência antes de ele ser preso e submetido a uma técnica de reabilitação psicológica.',
        genero: 'Crime, Drama, Ficção Científica',
        diretor: 'Stanley Kubrick',
        cast: 'Malcolm McDowell, Patrick Magee, Michael Bates',
        duracao: '136 minutos',
        rating: '8.3/10',
        streaming: 'HBO Max',
        link: 'https://www.imdb.com/title/tt0066921/'
    },
    {
        titulo: 'O Sexto Sentido',
        lancamento: '1999',
        descricao: 'Um psicólogo infantil trabalha com um garoto que pode ver e falar com os mortos. À medida que se envolvem, eles descobrem segredos perturbadores.',
        genero: 'Drama, Mistério, Thriller',
        diretor: 'M. Night Shyamalan',
        cast: 'Bruce Willis, Haley Joel Osment, Toni Collette',
        duracao: '107 minutos',
        rating: '8.1/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt0167404/'
    },
    {
        titulo: 'O Pianista',
        lancamento: '2002',
        descricao: 'Durante a ocupação nazista da Polônia, um talentoso pianista judeu luta para sobreviver no gueto de Varsóvia.',
        genero: 'Biografia, Drama, Guerra',
        diretor: 'Roman Polanski',
        cast: 'Adrien Brody, Thomas Kretschmann, Frank Finlay',
        duracao: '150 minutos',
        rating: '8.5/10',
        streaming: 'Amazon Prime Video',
        link: 'https://www.imdb.com/title/tt0253474/'
    },
    {
        titulo: 'Donnie Darko',
        lancamento: '2001',
        descricao: 'Um adolescente perturbado é guiado por visões de um coelho demoníaco que o leva a cometer uma série de crimes antes do fim do mundo.',
        genero: 'Drama, Mistério, Ficção Científica',
        diretor: 'Richard Kelly',
        cast: 'Jake Gyllenhaal, Jena Malone, Mary McDonnell',
        duracao: '113 minutos',
        rating: '8.0/10',
        streaming: 'Amazon Prime Video',
        link: 'https://www.imdb.com/title/tt0246578/'
    },
    {
        titulo: 'Django Livre',
        lancamento: '2012',
        descricao: 'Um escravo liberto se torna um caçador de recompensas e parte em busca de sua esposa enquanto se envolve em uma luta sangrenta contra seus opressores.',
        genero: 'Drama, Faroeste',
        diretor: 'Quentin Tarantino',
        cast: 'Jamie Foxx, Christoph Waltz, Leonardo DiCaprio',
        duracao: '165 minutos',
        rating: '8.4/10',
        streaming: 'Netflix',
        link: 'https://www.imdb.com/title/tt1853728/'
    },
    {
        titulo: 'Kill Bill: Volume 1',
        lancamento: '2003',
        descricao: 'Uma ex-assassina, conhecida como A Noiva, busca vingança contra o esquadrão de assassinos que tentou matá-la.',
        genero: 'Ação, Crime, Thriller',
        diretor: 'Quentin Tarantino',
        cast: 'Uma Thurman, David Carradine, Daryl Hannah',
        duracao: '111 minutos',
        rating: '8.2/10',
        streaming: 'Amazon Prime Video',
        link: 'https://www.imdb.com/title/tt0266697/'
    },
    {
        titulo: 'O Profissional',
        lancamento: '1994',
        descricao: 'Um assassino profissional cuida de uma jovem cujo pai foi assassinado por um agente corrupto da DEA.',
        genero: 'Crime, Drama, Thriller',
        diretor: 'Luc Besson',
        cast: 'Jean Reno, Gary Oldman, Natalie Portman',
        duracao: '110 minutos',
        rating: '8.5/10',
        streaming: 'Netflix',
        link: 'https://www.imdb.com/title/tt0110413/'
    },
    {
        titulo: 'Forrest Gump: O Contador de Histórias',
        lancamento: '1994',
        descricao: 'Um homem com um QI abaixo da média vive uma vida extraordinária, participando de grandes eventos históricos, ao mesmo tempo em que busca seu amor de infância.',
        genero: 'Drama, Romance',
        diretor: 'Robert Zemeckis',
        cast: 'Tom Hanks, Robin Wright, Gary Sinise',
        duracao: '142 minutos',
        rating: '8.8/10',
        streaming: 'Netflix',
        link: 'https://www.imdb.com/title/tt0109830/'
    },
    {
        titulo: 'Os Infiltrados',
        lancamento: '2006',
        descricao: 'Um policial disfarçado tenta se infiltrar na máfia enquanto um criminoso infiltrado na polícia tenta descobrir sua identidade.',
        genero: 'Crime, Drama, Thriller',
        diretor: 'Martin Scorsese',
        cast: 'Leonardo DiCaprio, Matt Damon, Jack Nicholson',
        duracao: '151 minutos',
        rating: '8.5/10',
        streaming: 'HBO Max',
        link: 'https://www.imdb.com/title/tt0407887/'
    },
    {
        titulo: 'Coração Valente',
        lancamento: '1995',
        descricao: 'A história do lendário herói escocês William Wallace, que liderou uma revolta contra o domínio inglês.',
        genero: 'Biografia, Drama, História',
        diretor: 'Mel Gibson',
        cast: 'Mel Gibson, Sophie Marceau, Patrick McGoohan',
        duracao: '178 minutos',
        rating: '8.3/10',
        streaming: 'Amazon Prime Video',
        link: 'https://www.imdb.com/title/tt0112573/'
    },
    {
        titulo: 'Corra!',
        lancamento: '2017',
        descricao: 'Um jovem negro visita a família de sua namorada branca e descobre segredos sinistros em sua propriedade, misturando terror psicológico com crítica social.',
        genero: 'Terror, Mistério, Thriller',
        diretor: 'Jordan Peele',
        cast: 'Daniel Kaluuya, Allison Williams, Bradley Whitford',
        duracao: '104 minutos',
        rating: '7.7/10',
        streaming: 'Amazon Prime Video',
        link: 'https://www.imdb.com/title/tt5052448/'
    },
    {
        titulo: 'O Jogo da Imitação',
        lancamento: '2014',
        descricao: 'Durante a Segunda Guerra Mundial, o matemático Alan Turing tenta quebrar o código Enigma da Alemanha Nazista com a ajuda de um grupo de matemáticos talentosos.',
        genero: 'Biografia, Drama, Thriller',
        diretor: 'Morten Tyldum',
        cast: 'Benedict Cumberbatch, Keira Knightley, Matthew Goode',
        duracao: '113 minutos',
        rating: '8.0/10',
        streaming: 'Amazon Prime Video',
        link: 'https://www.imdb.com/title/tt2084970/'
    },
    {
        titulo: 'Cisne Negro',
        lancamento: '2010',
        descricao: 'Uma bailarina se envolve em uma perigosa espiral de autodescoberta e autodestruição ao competir pelo papel principal em "O Lago dos Cisnes".',
        genero: 'Drama, Terror, Thriller',
        diretor: 'Darren Aronofsky',
        cast: 'Natalie Portman, Mila Kunis, Vincent Cassel',
        duracao: '108 minutos',
        rating: '8.0/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt0947798/'
    },
    {
        titulo: 'Her',
        lancamento: '2013',
        descricao: 'Um escritor solitário se apaixona por um sistema operacional de inteligência artificial projetado para atender todas as suas necessidades.',
        genero: 'Drama, Romance, Ficção Científica',
        diretor: 'Spike Jonze',
        cast: 'Joaquin Phoenix, Amy Adams, Scarlett Johansson',
        duracao: '126 minutos',
        rating: '8.0/10',
        streaming: 'HBO Max',
        link: 'https://www.imdb.com/title/tt1798709/'
    },
    {
        titulo: 'Gravidade',
        lancamento: '2013',
        descricao: 'Após um acidente em uma missão espacial, dois astronautas lutam para sobreviver e voltar à Terra.',
        genero: 'Drama, Ficção Científica, Thriller',
        diretor: 'Alfonso Cuarón',
        cast: 'Sandra Bullock, George Clooney, Ed Harris',
        duracao: '91 minutos',
        rating: '7.7/10',
        streaming: 'Amazon Prime Video',
        link: 'https://www.imdb.com/title/tt1454468/'
    },
    {
        titulo: 'Homem de Ferro',
        lancamento: '2008',
        descricao: 'Tony Stark, um bilionário e engenheiro genial, cria uma armadura de alta tecnologia para escapar de um sequestro e, posteriormente, decide usá-la para combater o mal.',
        genero: 'Ação, Aventura, Ficção Científica',
        diretor: 'Jon Favreau',
        cast: 'Robert Downey Jr., Gwyneth Paltrow, Jeff Bridges',
        duracao: '126 minutos',
        rating: '7.9/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt0371746/'
    },
    {
        titulo: 'Mulher-Maravilha',
        lancamento: '2017',
        descricao: 'Diana, uma guerreira amazona, deixa sua ilha paradisíaca para salvar o mundo de uma grande guerra e descobre seus verdadeiros poderes como a Mulher-Maravilha.',
        genero: 'Ação, Aventura, Fantasia',
        diretor: 'Patty Jenkins',
        cast: 'Gal Gadot, Chris Pine, Robin Wright',
        duracao: '141 minutos',
        rating: '7.4/10',
        streaming: 'HBO Max',
        link: 'https://www.imdb.com/title/tt0451279/'
    },
    {
        titulo: 'Pantera Negra',
        lancamento: '2018',
        descricao: "Após a morte de seu pai, T'Challa retorna a Wakanda para assumir seu lugar como rei, mas deve enfrentar um adversário que ameaça expor o reino ao mundo.",
        genero: 'Ação, Aventura, Ficção Científica',
        diretor: 'Ryan Coogler',
        cast: 'Chadwick Boseman, Michael B. Jordan, Lupita Nyong\'o',
        duracao: '134 minutos',
        rating: '7.3/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt1825683/'
    },
    {
        titulo: 'Vingadores: Ultimato',
        lancamento: '2019',
        descricao: 'Os Vingadores restantes tentam reverter a devastação causada por Thanos e restaurar o universo, enfrentando desafios épicos e pessoais.',
        genero: 'Ação, Aventura, Ficção Científica',
        diretor: 'Anthony Russo, Joe Russo',
        cast: 'Robert Downey Jr., Chris Evans, Mark Ruffalo',
        duracao: '181 minutos',
        rating: '8.4/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt4154796/'
    },
    {
        titulo: 'Homem-Aranha: No Aranhaverso',
        lancamento: '2018',
        descricao: 'Miles Morales, um adolescente do Brooklyn, se torna o Homem-Aranha e se junta a outras versões do herói de diferentes dimensões para salvar o multiverso.',
        genero: 'Animação, Ação, Aventura',
        diretor: 'Peter Ramsey, Rodney Rothman',
        cast: 'Shameik Moore, Jake Johnson, Hailee Steinfeld',
        duracao: '117 minutos',
        rating: '8.4/10',
        streaming: 'Netflix',
        link: 'https://www.imdb.com/title/tt4633694/'
    },
    {
        titulo: 'Logan',
        lancamento: '2017',
        descricao: 'Em um futuro próximo, um envelhecido Wolverine e um frágil Professor X tentam proteger uma jovem mutante de forças malignas, enquanto lidam com suas próprias crises pessoais.',
        genero: 'Ação, Drama, Ficção Científica',
        diretor: 'James Mangold',
        cast: 'Hugh Jackman, Patrick Stewart, Dafne Keen',
        duracao: '137 minutos',
        rating: '8.1/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt3315342/'
    },
    {
        titulo: 'Guardiões da Galáxia',
        lancamento: '2014',
        descricao: 'Um grupo de desajustados galácticos se une para proteger um artefato poderoso e evitar que ele caia nas mãos erradas, descobrindo o poder da amizade ao longo do caminho.',
        genero: 'Ação, Aventura, Comédia',
        diretor: 'James Gunn',
        cast: 'Chris Pratt, Zoe Saldana, Dave Bautista',
        duracao: '121 minutos',
        rating: '8.0/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt2015381/'
    },
    {
        titulo: 'Capitão América: O Soldado Invernal',
        lancamento: '2014',
        descricao: 'Steve Rogers, agora vivendo no mundo moderno, deve enfrentar uma nova ameaça de dentro da S.H.I.E.L.D., ao mesmo tempo que lida com um misterioso assassino conhecido como o Soldado Invernal.',
        genero: 'Ação, Aventura, Suspense',
        diretor: 'Anthony Russo, Joe Russo',
        cast: 'Chris Evans, Scarlett Johansson, Sebastian Stan',
        duracao: '136 minutos',
        rating: '7.8/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt1843866/'
    },
    {
        titulo: 'Aquaman',
        lancamento: '2018',
        descricao: 'Arthur Curry, meio humano e meio atlante, embarca em uma jornada para descobrir sua herança e assumir seu destino como rei de Atlântida.',
        genero: 'Ação, Aventura, Fantasia',
        diretor: 'James Wan',
        cast: 'Jason Momoa, Amber Heard, Willem Dafoe',
        duracao: '143 minutos',
        rating: '6.8/10',
        streaming: 'HBO Max',
        link: 'https://www.imdb.com/title/tt1477834/'
    },
    {
        titulo: 'Deadpool',
        lancamento: '2016',
        descricao: 'Um ex-militar e mercenário, Wade Wilson, passa por uma experiência que lhe dá habilidades de cura acelerada e uma nova identidade como o anti-herói Deadpool.',
        genero: 'Ação, Comédia',
        diretor: 'Tim Miller',
        cast: 'Ryan Reynolds, Morena Baccarin, T.J. Miller',
        duracao: '108 minutos',
        rating: '8.0/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt1431045/'
    },
    {
        titulo: 'Toy Story',
        lancamento: '1995',
        descricao: 'Quando o jovem Andy sai do quarto, seus brinquedos ganham vida. O xerife Woody sente seu mundo abalado quando um novo brinquedo, Buzz Lightyear, chega e se torna o preferido de Andy.',
        genero: 'Animação, Aventura, Comédia',
        diretor: 'John Lasseter',
        cast: 'Tom Hanks, Tim Allen, Don Rickles',
        duracao: '81 minutos',
        rating: '8.3/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt0114709/'
    },
    {
        titulo: 'Procurando Nemo',
        lancamento: '2003',
        descricao: 'Depois que seu filho é capturado e levado para Sydney, um peixe-palhaço superprotetor embarca em uma jornada épica ao lado de uma companheira amnésica para resgatá-lo.',
        genero: 'Animação, Aventura, Comédia',
        diretor: 'Andrew Stanton, Lee Unkrich',
        cast: 'Albert Brooks, Ellen DeGeneres, Alexander Gould',
        duracao: '100 minutos',
        rating: '8.2/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt0266543/'
    },
    {
        titulo: 'Os Incríveis',
        lancamento: '2004',
        descricao: 'Uma família de super-heróis tenta levar uma vida normal, mas é forçada a entrar em ação quando surge uma nova ameaça. Cada membro da família usa seus poderes para salvar o mundo.',
        genero: 'Animação, Ação, Aventura',
        diretor: 'Brad Bird',
        cast: 'Craig T. Nelson, Holly Hunter, Samuel L. Jackson',
        duracao: '115 minutos',
        rating: '8.0/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt0317705/'
    },
    {
        titulo: 'Ratatouille',
        lancamento: '2007',
        descricao: 'Um rato chamado Remy sonha em se tornar um grande chef de cozinha e encontra sua chance quando faz uma parceria improvável com um jovem trabalhador da cozinha em um famoso restaurante parisiense.',
        genero: 'Animação, Aventura, Comédia',
        diretor: 'Brad Bird, Jan Pinkava',
        cast: 'Brad Garrett, Lou Romano, Patton Oswalt',
        duracao: '111 minutos',
        rating: '8.1/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt0382932/'
    },
    {
        titulo: 'Up: Altas Aventuras',
        lancamento: '2009',
        descricao: 'Um idoso viúvo amarra milhares de balões à sua casa e parte em uma jornada para a América do Sul, levando um jovem escoteiro junto com ele. Juntos, eles encontram aventuras e aprendem lições de vida.',
        genero: 'Animação, Aventura, Comédia',
        diretor: 'Pete Docter, Bob Peterson',
        cast: 'Edward Asner, Jordan Nagai, John Ratzenberger',
        duracao: '96 minutos',
        rating: '8.3/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt1049413/'
    },
    {
        titulo: 'Divertida Mente',
        lancamento: '2015',
        descricao: 'Dentro da mente de uma jovem, cinco emoções tentam guiá-la através da vida cotidiana enquanto ela e sua família se mudam para uma nova cidade. As emoções precisam trabalhar juntas para ajudá-la a se adaptar.',
        genero: 'Animação, Aventura, Comédia',
        diretor: 'Pete Docter, Ronnie del Carmen',
        cast: 'Amy Poehler, Bill Hader, Lewis Black',
        duracao: '95 minutos',
        rating: '8.1/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt2096673/'
    },
    {
        titulo: 'Viva: A Vida é uma Festa',
        lancamento: '2017',
        descricao: 'Miguel, um jovem aspirante a músico, embarca em uma jornada pela Terra dos Mortos para descobrir o mistério da sua ancestralidade e entender o verdadeiro significado da família.',
        genero: 'Animação, Aventura, Família',
        diretor: 'Lee Unkrich, Adrian Molina',
        cast: 'Anthony Gonzalez, Gael García Bernal, Benjamin Bratt',
        duracao: '105 minutos',
        rating: '8.4/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt2380307/'
    },
    {
        titulo: 'Monstros S.A.',
        lancamento: '2001',
        descricao: 'Na fábrica de monstros onde sustos são gerados para fornecer energia, dois monstros descobrem uma menina humana e devem devolvê-la ao seu mundo enquanto evitam ser descobertos.',
        genero: 'Animação, Aventura, Comédia',
        diretor: 'Pete Docter, David Silverman',
        cast: 'Billy Crystal, John Goodman, Mary Gibbs',
        duracao: '92 minutos',
        rating: '8.1/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt0198781/'
    },
    {
        titulo: 'Carros',
        lancamento: '2006',
        descricao: 'Um carro de corrida egocêntrico chamado Relâmpago McQueen aprende lições de humildade e amizade ao se perder em uma pequena cidade enquanto viaja para uma importante corrida.',
        genero: 'Animação, Aventura, Comédia',
        diretor: 'John Lasseter, Joe Ranft',
        cast: 'Owen Wilson, Bonnie Hunt, Paul Newman',
        duracao: '117 minutos',
        rating: '7.2/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt0317219/'
    },
    {
        titulo: 'Valente',
        lancamento: '2012',
        descricao: 'Merida, uma princesa rebelde da Escócia, desafia a tradição e acidentalmente amaldiçoa sua mãe. Ela deve encontrar coragem para desfazer o feitiço e salvar seu reino.',
        genero: 'Animação, Aventura, Família',
        diretor: 'Mark Andrews, Brenda Chapman',
        cast: 'Kelly Macdonald, Billy Connolly, Emma Thompson',
        duracao: '93 minutos',
        rating: '7.1/10',
        streaming: 'Disney+',
        link: 'https://www.imdb.com/title/tt1217209/'
    }

];